In [1]:
import pandas as pd

In [ ]:
chagas_ano = pd.read_csv('C:\\Users\\Nathalie\\Chagas\\chagas-disease-data-analysis-4\\data\\Doença de Chagas - Regiao X Ano.csv', sep=';', encoding='utf-8')
chagas_ano.head()

,Regiao de notificacao,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,Total
0,1 Regiao Norte,17,112,148,196,146,205,269,355,332,355,350,162,324,387,526,502,4386
1,2 Regiao Nordeste,3,9,14,-,2,1,19,3,1,29,32,1,9,16,9,14,162
2,3 Regiao Sudeste,-,-,-,2,2,1,-,1,2,-,-,4,1,7,3,1,24
3,4 Regiao Sul,-,1,-,1,1,1,-,-,-,-,-,-,4,2,4,1,15
4,5 Regiao Centro-Oeste,1,14,8,-,1,1,-,-,3,-,3,1,2,3,1,2,40

In [11]:
chagas_faixa = pd.read_csv('C:\\Users\\Nathalie\\Chagas\\chagas-disease-data-analysis-4\\data\\Doença de Chagas - Regiao X Faixa Etaria.csv', sep=';', encoding='utf-8')
chagas_faixa.head()

,Regiao de notificacao,<1 Ano,1-4,5-9,10-14,15-19,20-39,40-59,60-64,65-69,70-79,80 e +,Total
0,1 Regiao Norte,53,190,328,380,378,1499,1087,155,122,150,44,4386
1,2 Regiao Nordeste,1,7,10,12,11,52,46,6,6,7,4,162
2,3 Regiao Sudeste,7,2,1,-,1,3,4,2,1,1,2,24
3,4 Regiao Sul,4,2,-,-,-,4,3,1,-,-,1,15
4,5 Regiao Centro-Oeste,1,-,-,-,-,9,24,1,3,1,1,40

In [12]:
chagas_via = pd.read_csv('C:\\Users\\Nathalie\\Chagas\\chagas-disease-data-analysis-4\\data\\Doença de Chagas - Regiao X Via.csv', sep=';', encoding='utf-8')
chagas_via.head()

,Regiao de notificacao,Ign/Branco,Vetorial,Vertical,Acidental,Oral,Outro,Total
0,1 Regiao Norte,422,272,3,5,3680,4,4386
1,2 Regiao Nordeste,40,29,-,1,92,-,162
2,3 Regiao Sudeste,8,2,8,2,1,3,24
3,4 Regiao Sul,2,3,4,1,2,3,15
4,5 Regiao Centro-Oeste,22,16,1,-,-,1,40

In [13]:
chagas_obitos_ano = pd.read_csv('C:\\Users\\Nathalie\\Chagas\\chagas-disease-data-analysis-4\\data\\Doença de Chagas - OBITOS - Regiao X Ano.csv', sep=';', encoding='utf-8')
chagas_obitos_ano.head()

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Nathalie\\Chagas\\chagas-disease-data-analysis-4\\data\\Doença de Chagas - OBITOS - Regiao X Ano.csv'